Repository JSConfCL/TechTon-landing, pull requests merged in 2024-02, with the labels that each got.

#20 update final
  README.md
Labels: bug

#21 feat: Add fonts to CSS (#19)
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
Labels: enhancement

#25 Feature/subtitle as h3
  src/app/page.js
  src/components/Subtitle/Subtitle.js
Labels: enhancement

#29 metadata title from "Create Next App" to "TechTon | JsChile"
  src/app/layout.js
Labels: Frontend, enhancement

#36 fixing some text responsiveness problems
  src/app/page.js
  src/components/Subtitle/Subtitle.js
  src/components/Title.jsx
Labels: enhancement

#41 feat: Create Twitch Button Component and Add to Home (#11)
  public/twitch_logo.svg
  src/app/layout.js
  src/app/page.js
  src/components/TwitchButton.jsx
Labels: enhancement

#46 Feature/12
  public/footer/chilean-flag.svg
  public/footer/icon-calendar.svg
  public/footer/icon-clock.svg
  public/footer/icon-hands.svg
  src/app/layout.js
  src/app/page.js
  src/components/Footer.jsx
  src/components/TwitchButton.jsx
  src/components/counterSubtitle.jsx
Labels: enhancement

#58 feat: add donar route
  src/app/donar/page.js
  src/app/page.js
  src/components/AgendaLogo.jsx
  src/components/Title.jsx
Labels: Frontend, enhancement

#76 Talks list
  src/talks/talks.json
Labels: Backend

#80 fet: se añade componente Logo :zap:
  src/app/layout.js
  src/app/page.js
  src/components/Logo.jsx
Labels: Frontend, bug

#78 Solving image issues in agenda
  src/components/Timeline.jsx
Labels: Frontend, enhancement

#82 fix: svg logo
  src/components/Logo.jsx
Labels: Frontend, bug, enhancement, good first issue

#83 modify: donate route button
  src/app/page.js
Labels: Frontend, enhancement

#84 modify: logo for /donar route
  src/app/donar/page.js
Labels: Frontend, enhancement

#85 Feature/61
  src/app/agenda/page.js
  src/app/donar/page.js
  src/app/page.js
  src/components/Logo.jsx
  src/components/Title.jsx
Labels: Frontend, bug

#87 fix duplicated viewbox
  src/app/page.js
  src/components/Subtitle/Subtitle.js
  src/components/Title.jsx
Labels: bug

#93 Fix/title
  src/app/agenda/page.js
  src/app/page.js
  src/components/AgendaLogo.jsx
  src/components/Logo.jsx
  src/components/Subtitle/Subtitle.js
  src/components/Title.jsx
Labels: Frontend, bug

#104 fix: Cambiar texto de botones del timeline (#103)
  src/app/agenda/page.js
Labels: Frontend, enhancement

#112 feature: Agregar botones a página de donar (#72)
  src/app/donar/page.js
Labels: Frontend, enhancement

#149 closes #146
  src/talks/talks.json
Labels: Backend, Frontend

#133 Feature/add about page
  public/images/communities/CommunityOS.webp
  public/images/communities/El-Club-de-la-IA.webp
  public/images/communities/logo-js.webp
  public/images/communities/logo-mermelada-tech.webp
  src/app/agenda/page.js
  src/app/layout.js
  src/app/nosotros/page.js
  src/app/page.js
  src/communities/communities.json
  src/components/NavBar.jsx
Labels: Frontend, enhancement

#241 bunch-o-thingies
  .prettierrc
  package-lock.json
  package.json
  public/images/bomberos-bg-2.webp
  public/images/bomberos-bg.webp
  public/images/communities/pythonchile_logo.webp
  public/images/icons/handshake.svg
  src/app/_app.js
  src/app/agenda/client-page.js
  src/app/donar/page.js
  src/app/layout.js
  src/app/nosotros/page.js
  src/app/page.js
  src/components/CommunityLogos/index.js
  src/components/CountdownTimer.jsx
  src/components/CounterSubtitle.jsx
  src/components/DonarSubtitulo.jsx
  src/components/DonateInfo.jsx
  src/components/FadeInBackgroundImages.jsx
  src/components/Footer.jsx
  src/components/NavBar.jsx
  src/components/NumberBox.jsx
  src/components/Subtitle/Subtitle.js
  src/components/Timeline.jsx
  src/components/Title.jsx
  src/components/hooks/useCssTransitionOnView.js
  src/helpers/api.js
Labels: Frontend

#258 remove donate section and modify texts
  src/app/page.js
  src/components/CounterSubtitle.jsx
  src/components/DonarSubtitulo.jsx
  src/components/DonateInfo.jsx
  src/components/NavBar.jsx
Labels: Frontend
